import type { StoryGraph } from "../types.js";

export function toMermaid(
	graph: StoryGraph,
	options: {
		includeMetadata?: boolean;
		style?: "default" | "dark" | "minimal";
	} = {},
): string {
	let out = `%% Mermaid diagram generated by bl1nk-visual-mcp\n`;
	if (options.includeMetadata !== false)
		out += `%% Title: ${graph.meta.title}\n`;

	const theme =
		options.style === "dark"
			? "dark"
			: options.style === "minimal"
				? "neutral"
				: "default";
	out += `%%{init: {'theme': '${theme}'}}%%\n`;

	out += "graph TD\n";

	// 1. Group events by Act
	const acts: Record<number, any[]> = { 1: [], 2: [], 3: [] };
	graph.events.forEach((e) => {
		if (!acts[e.act]) acts[e.act] = [];
		acts[e.act].push(e);
	});

	// 2. Render Subgraphs for Acts
	([1, 2, 3] as const).forEach((act) => {
		if (acts[act].length === 0) return;
		out += `  subgraph Act_${act} ["Act ${act}"]\n`;
		acts[act]
			.sort((a, b) => a.sequenceInAct - b.sequenceInAct)
			.forEach((e) => {
				const label = e.label.replace(/"/g, "'");
				// Different shapes for different importance
				let shape = `["${label}"]`;
				if (e.importance === "climax") shape = `(("${label}"))`;
				if (e.importance === "midpoint") shape = `> "${label}" ]`;
				if (e.importance === "inciting") shape = `{{ "${label}" }}`;

				out += `    ${e.id}${shape}:::${e.importance}\n`;
			});
		out += "  end\n";
	});

	// 3. Connect events in sequence
	const sortedEvents = [...graph.events].sort((a, b) => {
		if (a.act !== b.act) return a.act - b.act;
		return a.sequenceInAct - b.sequenceInAct;
	});

	for (let i = 0; i < sortedEvents.length - 1; i++) {
		out += `  ${sortedEvents[i].id} --> ${sortedEvents[i + 1].id}\n`;
	}

	// 4. Character interactions (optional, can be messy in flowchart)
	// graph.relationships.forEach(r => out += `  ${r.from} -.-> ${r.to}\n`);

	// 5. Styling
	out += "\n  classDef inciting fill:#f9f,stroke:#333,stroke-width:2px\n";
	out += "  classDef midpoint fill:#ff9,stroke:#333,stroke-width:2px\n";
	out += "  classDef climax fill:#f96,stroke:#333,stroke-width:4px\n";
	out += "  classDef resolution fill:#9f9,stroke:#333,stroke-width:2px\n";
	out += "  classDef rising fill:#fff,stroke:#333,stroke-width:1px\n";

	return out;
}
