import { StoryGraph } from './types.js';

export function toMermaid(graph: StoryGraph, options: { includeMetadata?: boolean; style?: string } = {}): string {
  let out = `%% Mermaid diagram generated by Visual Story Planner\n`;
  if (options.includeMetadata !== false) out += `%% Title: ${graph.meta.title}\n`;
  if (options.style === 'dark') out += "%%{init: {'theme': 'dark'}}%%\n";
  out += 'graph TD\n';

  const acts = { 1: [] as any[], 2: [] as any[], 3: [] as any[] };
  graph.events.forEach(e => acts[e.act as 1|2|3]?.push(e));

  ([1, 2, 3] as const).forEach(act => {
    if (acts[act].length === 0) return;
    out += `subgraph Act_${act}["Act ${act}"]\n`;
    acts[act].forEach(e => {
      const label = e.label.replace(/"/g, "'");
      out += `  ${e.id}["${label}"]:::${e.importance}\n`;
    });
    out += 'end\n';
  });

  graph.relationships.forEach(r => out += `${r.from} --> ${r.to}\n`);
  out += '\nclassDef inciting fill:#f9f,stroke:#333,stroke-width:2px\n';
  out += 'classDef midpoint fill:#ff9,stroke:#333,stroke-width:2px\n';
  out += 'classDef climax fill:#f96,stroke:#333,stroke-width:4px\n';
  out += 'classDef resolution fill:#9f9,stroke:#333,stroke-width:2px\n';
  
  // Wrap in artifact format
  return `\`\`\`artifact
id: vsp3_mermaid_diagram
name: ${graph.meta.title.replace(/\s+/g, '_')}_Mermaid_Diagram
type: code.mermaid
content: |-
${out.split('\n').map(line => '  ' + line).join('\n')}
\`\`\``;
}
